name: mplayer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  path_provider: ^2.1.5
  path: ^1.9.1
  dio: ^5.9.1
  chopper: ^8.5.0
  json_annotation: ^4.10.0
  freezed_annotation: ^3.1.0
  google_fonts: ^8.0.1
  dynamic_color: ^1.8.1
  animations: ^2.1.1
  google_generative_ai: ^0.4.7
  audio_service: ^0.18.18
  just_audio: ^0.10.5
  workmanager: ^0.9.0+3
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  audio_session: ^0.2.2
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  flutter_animate: ^4.5.2
  go_router: ^17.1.0
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.6.0+eol
  audio_metadata_reader: ^1.4.2
  home_widget: ^0.9.0
  palette_generator: ^0.3.3+7
  webview_flutter: ^4.13.1
  youtube_explode_dart: ^3.0.5
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  riverpod_generator: ^4.0.3
  chopper_generator: ^8.6.0
  json_serializable: ^6.12.0
  freezed: ^3.2.5


flutter:
  uses-material-design: true
